### ISSUE TITLE
How to call this manually?

### ISSUE THREAD

**Issue by gtamas** [pinojs/pino-http#101]
I have a Koa middleware. In that I create a http-logger instance like so:

```
   app.use(async (ctx, next) => {
    const logger = require('pino-http')({...}) 
    logger(ctx.req, ctx.res)
   await next();
   }
```
   
Now, this works fine if autoLogging=true.
When it's false, however, calling ctx.log.info(...)  produces a standard pino log entry, without request ./ response and the other fields.

I would like to execute the HTTP logger manually, so it logs only when I need it. How can I do that?

**Comment by gtamas** [comment]
OK figured out that I actually called the wrong method... never mind, 

But

Calling **req**.log.info(...) results in the request data being logged, but calling **res**.log.info() does not add the response data. Like the previous one, it logs request data!

So in both cases, I get this:

`{"level":30,"time":1589901106757,"pid":31326,"hostname":"some","req":{"PID":"0e7424e0-99e3-11ea-ac46-5175f0f8298a"},"msg":"some msg"}`

How do I add the response data without autoLogging??

Please help!

**Comment by mcollina** [comment]
You should not be logging the response. It often contains personal information and logging them would violate GDPR and other things.

If you want to do so anyway, you should cange the `res` serializer.

```js
var logger = require('pino-http')({
  // Define custom serializers
  serializers: {
    res (obj) {
      // fill in!
    }
  }
})
```
