### ISSUE TITLE
Property to be logged per request level but outside req

### ISSUE THREAD

**Issue by samjeyam** [pinojs/pino-http#102]
Is there a way to log something outside the `req`  but within the request Serializer.

```
const reqSerializer = (req) =>  {
  return Object.assign(
    pinoHttp.stdSerializers.req(req),
    { correlationId: req.correlationId});
};
```

I have a requirement where I would like to log something like this

```
{
   "level":30,
   "@timestamp":"2020-05-22T01:35:37.177Z",
   "pid":xxxx,
   "hostname":"xxxxxx",
   "req":{
      "method":"GET",
      "endpoint":"/api/v1/greetings?name=xyz",
      "request_id":"xxxxx"
   }, 
   "description":"getHelloWorld()",
   "correlationId": "some-request-specific-value" <-- would like to log it here and not within "req"
}
```

Btw, `mixin` doesn't help my use-case where it's pretty static for all requests and not per request.

**Comment by mcollina** [comment]
> Is there a way to log something outside the req but within the request Serializer. 

Unfortunately there is not. However we could potentially add something here to intercept where a child logger is created. In that case, you might be able to add properties to the child logger.

**Comment by samjeyam** [comment]
Pls review https://github.com/pinojs/pino-http/pull/103 if that make sense.

**Comment by samjeyam** [comment]
This can be closed now. 
v5.2.0 now has this feature.

thank you @mcollina
