### ISSUE TITLE
Disable output when NODE_ENV === 'test'

### ISSUE THREAD

**Issue by giacomorebonato** [pinojs/pino-http#105]
Hi, I am trying to disable output when running tests with the code below:

```ts
export const logger = pino({
  enabled: process.env.NODE_ENV !== ENV.TEST
})

const pino = Pino({
  autoLogging: process.env.NODE_ENV !== ENV.TEST,
  logger,
  prettyPrint: process.env.NODE_ENV !== ENV.PROD,
  enabled: process.env.NODE_ENV !== ENV.TEST
})
```

With the code above the log for requests is still present in the output, while the other log lines are correctly hidden.
I am writing integration tests for an Express server that is started by the test.

Am I missing something or is it something that I could take a look on?

**Comment by mcollina** [comment]
I'm not sure we support an `enabled` property. You can set the level to `silent` for unsupported envs.

**Comment by giacomorebonato** [comment]
OK, that works too. Thanks.
