### ISSUE TITLE
feat request: autologging ignore user agent

### ISSUE THREAD

**Issue by naseemkullah** [pinojs/pino-http#107]
the ignore path option is great for health check paths, sometimes external probes actually probe production paths used to serve traffic to users, in these cases it would be nice to ignore 200s based on user agent

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by naseemkullah** [comment]
In fact, customLogLevel suits our needs, we will simply decrease log level of 2xx to debug as follows:

```js
    customLogLevel: (res, err) => {
      if (res.statusCode >= 200 && res.statusCode < 300) {
        return 'debug';
      } else if (res.statusCode >= 300 && res.statusCode < 400) {
        return 'info';
      } else if (res.statusCode >= 400 && res.statusCode < 500) {
        return 'warn';
      } else if (res.statusCode >= 500 || err) {
        return 'error';
      } else {
        return 'info';
      }
    },
```

**Comment by naseemkullah** [comment]
closed via https://github.com/pinojs/pino-http/pull/153
