### ISSUE TITLE
node-spdy's HTTP/2 (https) support

### ISSUE THREAD

**Issue by Hongbo-Miao** [pinojs/pino-http#112]
Thanks for the awesome package!

It works on `http`, but currently does not log anything when using HTTP/2 by [node-spdy](https://github.com/spdy-http2/node-spdy).

**Comment by mcollina** [comment]
SPDY is not supported.

**Comment by Hongbo-Miao** [comment]
Thanks for confirming @mcollina !
It would be great to have support, but definitely low priorty : )
Because when I switched from [winston](https://github.com/winstonjs/winston) and [Cabin](https://github.com/cabinjs/cabin) to pino. I am using node-spdy to simulate HTTPS (I am using [node-spdy](https://github.com/spdy-http2/node-spdy) for **HTTP/2** instead of **SPDY**) on localhost.
When I switched to pino, I spent a while to figure out why it is not logged.

**Comment by Hongbo-Miao** [comment]
On second thought, I have switched to http instead of https for local dev. Instead, I am using NGINX or similar solutions as gate. This way is more close to production.

Close as I feel not needed. Thanks!
