### ISSUE TITLE
Custom properties in Fastify logging

### ISSUE THREAD

**Issue by YuriGal** [pinojs/pino-http#118]
Not an issue, but rather a request. I am using Fastify (which uses Pino under the hood for logging) and would like to add custom request properties to the log whenever something like `req.log.info(...)` is called. I assumed `reqCustomProps` should be used for that, but can't seem to wire it properly. Would it be possible to provide an example of adding custom properties to Fastify logging?

**Comment by mcollina** [comment]
Fastify has its own adapter for http logging and it does not use this module.
