### ISSUE TITLE
Add res properties to custom props

### ISSUE THREAD

**Issue by josh-hemphill** [pinojs/pino-http#119]
The function `reqCustomProps` only has access to the `req` object, but best practice is to store data scoped to the request in `res.locals`, to which there is no access in `reqCustomProps`.
Does `res.locals` automatically get logged?
If not I'd be happy to open a pull request as it seems like by either just adding the `res` parameter to the function, or adding another similar function named appropriately, it should have minimal impact on current users' implementations.

**Comment by mcollina** [comment]
Go for it!
