### ISSUE TITLE
Warning: bindings.serializers is deprecated, use options.serializers option instead

### ISSUE THREAD

**Issue by Milad** [pinojs/pino-http#147]
It seems that `pino-http` is using a deprecated method to wrap the serializes.

Part of the stack trace:
```
(node:17122) [PINODEP004] Warning: bindings.serializers is deprecated, use options.serializers option instead
    at Pino.child (node_modules/pino/lib/proto.js:90:13)
    at wrapChild (node_modules/pino-http/logger.js:144:25)
    at pinoLogger (node_modules/pino-http/logger.js:59:16)
```

My usage (from two files actually):

```javascript
const logger = pino({
  name: 'name',
})

const child = logger.child({
  env: process?.env?.NODE_ENV ?? 'development'
})

const httpLogger = pinoHttp({
  logger: child
})
```

**Comment by kibertoad** [comment]
https://github.com/pinojs/pino-http/issues/144 -> same thing?..

**Comment by Milad** [comment]
Yes, it's the same. And the mentioned fix works. But, it's better to use `pino` as it should be used?

**Comment by kibertoad** [comment]
@Milad wasn't it fixed in the last version?

**Comment by Milad** [comment]
It's actually fixed! I haven't seen the latest version. Thanks for letting me know! This one is on me!
