### ISSUE TITLE
after updating to 5.6.0, all req and res properties are being logged

### ISSUE THREAD

**Issue by pkeuter** [pinojs/pino-http#152]
After updating to version 5.6.0, I see every single property in the request and response object when logging which makes the output possibly a bit too verbose. Downgrading to 5.5 resolves the issue.

I think this might be a regression since I don't see any information about this in the changelog.

**Comment by kibertoad** [comment]
Do you use child loggers?
Wonder if https://github.com/pinojs/pino-http/commit/967f2a69817346778eb0cbb49d7689b6152d4b3c is related.

**Comment by kibertoad** [comment]
Can you share simple reproduction code?

**Comment by pkeuter** [comment]
Looks I have been a little too quick blaming pino-http. Sorry about that. After removing node_modules and running `npm install` everything is working fine again.
