### ISSUE TITLE
disable logging of "req" object

### ISSUE THREAD

**Issue by schealex** [pinojs/pino-http#154]
Hi everyone, i've got the problem that my logs still sometimes include the "req" object.
I've configured pinohttp to reformat it to undefined because we have custom props for the relevant information.

Can someone explain how to remove the default log attributes like "req"?

```
pinoHttp({
      level: options.level,
      prettyPrint: options.prettyPrint,
      redact: options.redact,
      autoLogging: {
        ignorePaths: options.ignorePaths,
      },
      genReqId: function (req) {
        req.id = uuidv4();
        return req.id;
      },
      timestamp: () => `,"time":"${new Date(Date.now()).toISOString()}"`,
      reqCustomProps: (req: UserRequest, res: express.Response) => {
        return {
          appName: options.appName,
          appVersion: options.appVersion,
          reqId: req.id,
          reqMethod: req.method,
          reqUrl: req.baseUrl,
          reqQuery: req.query,
          reqParams: req.params,
          reqUserAgent: `${req.header('user-agent')}@${req.ip}`,
          correlationId: req.header('x-correlation-id'),
          userId: req.user?.userId || undefined,
          apiKeyId: req.user?.apiKeyId || undefined,
          sessionId: req.user?.sessionId || undefined,
          server: os.hostname(),
          statusCode: res.statusCode,
          contentType: res.getHeader('content-type') || undefined,
          contentLength: res.getHeader('content-length') || undefined,
        };
      },
      formatters: {
        level: (label) => {
          return { level: label };
        },
        log: (object: Record<string, unknown>) => {
          return {
            payload: {
              ...object,
              responseTime: undefined,
              req: undefined,
              res: undefined,
              _res: undefined,
              context: undefined,
            },
            req: undefined,
            context: object?.context,
            responseTime: object?.responseTime,
          };
        },
      },
    }),
```

**Comment by mcollina** [comment]
I don't think it's possible. I would recommend to avoid this module completely if such a big customization is required.

**Comment by schealex** [comment]
how would you realise this without pinohttp? Just with pino? and build a custom middleware for the http logging?

I don't understand why it's behaving this way anyways. I still think this might be a bug. In my library with the above config, there is never a req / res in the log. So the config works as expected. But once i include the library in another project, there are req in the log again.

**Comment by mcollina** [comment]
fork pinoHttp and build it the way you like.

> I don't understand why it's behaving this way anyways. I still think this might be a bug. In my library with the above config, there is never a req / res in the log. So the config works as expected. But once i include the library in another project, there are req in the log again.

Can you please prepare a running example?

**Comment by jsumners** [comment]
The point of this library is to add request logging to a HTTP service built on the core `http` API. Removing request logging defeats the point of this module.

**Comment by bfsmith** [comment]
This is very easy to do.
```js
pinoHttp({
  // ...
  serializers: {
    req() {
      return undefined; // Remove 'req' from logs
    },
  },
});
```
