### ISSUE TITLE
How to log response body?

### ISSUE THREAD

**Issue by ryan-efendy** [pinojs/pino-http#173]
How to use the serializer to log the response body? Can you share an example?

**Comment by mcollina** [comment]
I'm sorry but I do not have time :(. You should not log your bodies for both security and privacy of your users.

**Comment by naseemkullah** [comment]
@ryan-efendy  After considering @mcollina's advice, if you still want to and are using express you need something like https://github.com/richardschneider/express-mung to add the res body to the res object, then configure a serializer similar to the one for req body here https://github.com/pinojs/pino-http/pull/76/files

**Comment by Armas0n** [comment]
You could achieve that with 2 steps:

` // 1. create a res body hook
export const responseBodyHookMiddleware = (req: Request, res: Response, next: NextFunction) => {
  const originalJson = res.json;
  const originalSend = res.send;

  if (!res.locals) {
    res.locals = {};
  }

  res.json = function (data) {
    res.locals.responseBody = structuredClone(data);
    return originalJson.call(this, data);
  };

  res.send = function (data) {
    if (typeof data === 'object' && data !== null) {
      res.locals.responseBody = structuredClone(data);
    } else {
      res.locals.responseBody = data;
    }
    return originalSend.call(this, data);
  };

  next();
};`

// 2. Setup to serialize res body (in my example there is both req and res body logged)
export const loggerMiddleware = pinoHttp({
  logger,
  serializers: {
    req(req) {
      return {
        ...pino.stdSerializers.req(req),
        body: req.raw.body || null,
      };
    },
    res(res) {
      return {
        ...pino.stdSerializers.res(res.raw),
        body: JSON.parse(res.raw.locals.responseBody || '{}'),
      };
    },
  },
});

// then in your app.js
const app = express();

// middlewares
app.use(express.json());
app.use(responseBodyHookMiddleware);
app.use(loggerMiddleware);`
