### ISSUE TITLE
Pino 7 TypeScript

### ISSUE THREAD

**Issue by rstrand** [pinojs/pino-http#175]
Now pino 7 is including TypeScript types, would it make sense to include TypeScript types in this package as well? The types in DefinitelyTyped for this package don't work with the pino 7 types.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

cc @kibertoad

**Comment by rstrand** [comment]
I don't have any experience adding types to a project. Would it be acceptable to copy the types from definitely typed and fix the errors?

**Comment by gkampitakis** [comment]
Hello 👋 are there any updates on this issue? Are types going to be included in `pino-http`? I wouldn't mind trying and start a pr with your help

**Comment by mcollina** [comment]
A PR would be nice.

**Comment by jarcodallo** [comment]
> A PR would be nice.

Hi @mcollina, I opened a PR with the type definition. let me know what do you think. 🚀

**Comment by oddeirik** [comment]
Am I missing some required changes after the typings now being included in the package itself?

The IncomingMessage declaration for a 'req' property is missing in types now, which means TS will complain about doing `req.log.info()' in Express handlers/middleware.

This module declaration was included in the typings from @types/pino-http, but does not exist in the typings included in pino-http itself now:

```
declare module 'http' {
    interface IncomingMessage {
        id: PinoHttp.ReqId;
        log: Logger;
    }

    interface ServerResponse {
        err?: Error | undefined;
    }

    interface OutgoingMessage {
        [PinoHttp.startTime]: number;
    }
}
```

**Comment by kibertoad** [comment]
@oddeirik Would you like to send a PR to fix this?

**Comment by umarov** [comment]
https://github.com/pinojs/pino-http/pull/184 I think this one "removed" some PinoHttp.Options from types. They aren't being merged properly. I am using NestJS Pino Logger and using the redact option. It was yelling at me once I upgraded to the latest version. Moving back to `6.3.0` fixed it. I haven't figured out how that PR could have broken the types. I need to take a look again and see if I can make a PR.

**Comment by jarcodallo** [comment]
> #184 I think this one "removed" some PinoHttp.Options from types. They aren't being merged properly. I am using NestJS Pino Logger and using the `redact` option.
> 
> ```ts
> LoggerModule.forRoot({
>       pinoHttp: [
>         {
>           redact: [
>             'req.headers.authorization',
>             'req.headers.cookie',
>             'req.headers["x-csrf-token"]'
>           ]
>         }
>       ]
>     }),
> ```
> 
> It was yelling at me once I upgraded to the latest version. Moving back to `6.3.0` fixed it. I haven't figured out how that PR could have broken the types. I need to take a look again and see if I can make a PR.

Yeah. I'm working on a fix for this in nestjs-pino, but first I need #188 merge into master

**Comment by jarcodallo** [comment]
@umarov I open a PR in [nestjs-pino](https://github.com/iamolegga/nestjs-pino/pull/699) to fix the problem.

**Comment by mbrevda** [comment]
Was this ever resolved? Currently grappling with:
<img width="595" alt="Screen Shot 2023-01-24 at 6 47 58 PM" src="https://user-images.githubusercontent.com/293004/214355450-80a09f68-ab3b-42e6-a1ce-911546c19cbc.png">

**Comment by mcollina** [comment]
This was done long ago. Please open a fresh issuez
