### ISSUE TITLE
How to ignore autoLogging by statusCode or res?

### ISSUE THREAD

**Issue by filoscoder** [pinojs/pino-http#190]
I'm trying to use `autoLogging` conditionally by `res.statusCode` without success.

It would be great if something like this would be available:

```typescript
import expressPino from 'express-pino-logger';

export const expressPinoLogger = expressPino({
  autoLogging: {
    ignore: (req, res) => {
       return res.statusCode !== 200;
    }
  }
});
```

**Comment by jsumners** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by filoscoder** [comment]
> Would you like to send a Pull Request to address this issue? Remember to add unit tests.

I think this [PR](https://github.com/pinojs/pino-http/pull/113) is very handy for what I need to achieve.

I really like the autoLogging feature with serializers, but I don't want making this super fast logger keep logging statusCode 200, I just want to see the 400 <= codes to have evidence and hints for debugging my server.

**Comment by filoscoder** [comment]
Please take a look @jsumners 

https://github.com/pinojs/pino-http/pull/191
