### ISSUE TITLE
Logging responseTime in the message

### ISSUE THREAD

**Issue by francisdb** [pinojs/pino-http#199]
## Use case

We want to log request time in the log message

## Code

```js
function customSuccessMessage (res) {
  return `request completed ${res.req.method} ${res.req.url} ${res.statusCode} ${???.responseTime}ms`
}
```

we are looking for something we can put at `???`

## Context

Of course we want this responseTime to be the same as what is added in the log context

https://github.com/pinojs/pino-http/blob/5be1d8d9002f3ea9f4588dcd96826c7554e799c4/logger.js#L117-L119

As far as I can see this is not available in the context of customErrorMessage/customSuccessMessage, unless you duplicate the code that adds it to the log line context. With a chance of both values to be different.

https://github.com/pinojs/pino-http/blob/8232e17f32e6852422e84707fef99e298910f7ad/logger.js#L91

**Comment by mcollina** [comment]
I don't understand this issue, could you please clarify?

**Comment by francisdb** [comment]
> I don't understand this issue, could you please clarify?

Should indeed have done a better job describing the issue, I edited the description.

**Comment by mcollina** [comment]
Good spot! Would you like to send a PR?

**Comment by francisdb** [comment]
How do you see this passed to `customSuccessMessage` function? Some kind of extra context object argument?
