### ISSUE TITLE
aborted is not always an error

### ISSUE THREAD

**Issue by ronag** [pinojs/pino-http#20]
e.g. for `GET` and `HEAD` it doesn't make sense to log 'aborted' as an error?

**Comment by mcollina** [comment]
@ronag this is where it is handled: https://github.com/pinojs/pino-http/blob/master/logger.js#L49-L53.

What do you propose? Would you like to send a PR?

**Comment by ronag** [comment]
I don't think there is a way in NodeJS to differentiate between client and server `aborted`.

**Comment by mcollina** [comment]
> I don't think there is a way in NodeJS to differentiate between client and server aborted. When the client aborts, printing an error with 418 is confusing.

What do you mean?

**Comment by ronag** [comment]
@mcollina: There are two scenarios where an "aborted" event is emitted.

1. Server aborts due to timeout setting. The current behaviour is correct for this case.
2. The client chooses to abort the request. The current behaviour is confusing for this case. It's not a timeout and it's not an error for `GET` and `HEAD` requests.

**Comment by davidmarkclements** [comment]
Perhaps we can listen for a `close` event in the for detecting client abort... 

Perhaps also veryifing by listening for a `timeout` on the server object for socket server side timeouts

**Comment by davidmarkclements** [comment]
although we're going to want to handle this in the most performant way of course.. 

@ronag can you point to a spec doc detailing a 408 not being an error for `GET` and `HEAD` ?

**Comment by ronag** [comment]
@davidmarkclements: A *client* aborting GET or HEAD is not a server error since they should be side effect free.

**Comment by ronag** [comment]
regardless of the verb, a client aborting is not a timeout

**Comment by mcollina** [comment]
@ronag I still do not know yet how to fix this, and what do you propose. Also, #21 was closed.
Would you like to submit a PR with unit tests? You investigated this issue with much more details than us.

**Comment by ronag** [comment]
@mcollina I don't know yet.

**Comment by ronag** [comment]
@mcollina #22
