### ISSUE TITLE
Types missing for `Options.customProps`

### ISSUE THREAD

**Issue by k2snowman69** [pinojs/pino-http#213]
The option `customProps` is defined here:
https://github.com/pinojs/pino-http/blob/master/README.md?plain=1#L110

However is missing in the Options object
https://github.com/pinojs/pino-http/blob/master/index.d.ts#L35

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by salesh** [comment]
It's resolved in https://github.com/pinojs/pino-http/pull/211/files
