### ISSUE TITLE
deprecate autoLogging.ignorePaths / autoLogging.getPaths in favor of autoLogging.ignore?

### ISSUE THREAD

**Issue by naseemkullah** [pinojs/pino-http#217]
`autoLogging.ignore` can ignore by any req prop, including but not limited to `url`/`originalUrl`, as such should we deprecate `autoLogging.ignorePaths` / `autoLogging.getPaths`  or consider these to be convenience options?

**Comment by mcollina** [comment]
That'd be great, would you like to send a PR?

**Comment by naseemkullah** [comment]
Sure, #218 opened, PTAL
