### ISSUE TITLE
Remove PINOHTTP_DEP001 and PINOHTTP_DEP002

### ISSUE THREAD

**Issue by mcollina** [pinojs/pino-http#228]
Their time is overdue and the deprecated functionality should be removed.

**Comment by Puppo** [comment]
Hi @mcollina,
Can I help you with this?

**Comment by mcollina** [comment]
Go for it!

**Comment by vikaspotluri123** [comment]
@mcollina now that #229 is merged, can this be closed?

**Comment by mcollina** [comment]
good spot, thanks!
