### ISSUE TITLE
Double up of 'success' messages

### ISSUE THREAD

**Issue by Simon-Campbell** [pinojs/pino-http#234]
# Summary
I have upgraded from 6.6.x to 8.0.1. 

https://github.com/pinojs/pino-http/compare/v6.6.0...v8.0.1

All seems to be going ok, but I observed the following PR (https://github.com/pinojs/pino-http/pull/219) seems to have added an extra listener. This seems to be causing some double ups in 'success' message logging.

The situation I am using this for is to have clear start/end markers on requests, but this doubles up the number of end markers.

Is there a built-in way to reliably suppress this double up so that it behaves like 6.6.x? I don't have a small repro as my efforts to produce one are not working, so hoping someone more knowledgeable may know what's going on.

I run a Node v14 application.

# Update:

## Repro
https://github.com/Simon-Campbell/pino-http-double-success

## Key Change
Incompatibility with cls-rtracer

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by holzerch** [comment]
I have the exact same problem after upgrading from 7.0.0 to 7.1.0 when PR https://github.com/pinojs/pino-http/pull/219 was released. As a result the `onResFinished` function is called twice. Once for the `finish` event and once for the `close` event. 

I tested this with node 14 and 16 and koa 2.13.0 integrated as middleware.

**Comment by Simon-Campbell** [comment]
> Thanks for reporting!
> 
> Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

I attempted to create a Docker image reproducing this but failed to do so. I tried with express + node14... my actual application is built on NestJS, but I am a bit time poor at the moment to push my repro any further. 

Interesting to note that you had the same issue with a different Node version + different framework.

**Comment by holzerch** [comment]
> I have the exact same problem after upgrading from 7.0.0 to 7.1.0 when PR #219 was released. As a result the `onResFinished` function is called twice. Once for the `finish` event and once for the `close` event.
> 
> I tested this with node 14 and 16 and koa 2.13.0 integrated as middleware.

These are the call stack for the 2 calls to onResFinished when debugging and having a breakpoint at the beginning of the function:

First:
<img width="298" alt="image" src="https://user-images.githubusercontent.com/38455621/176118654-22488b5a-5cd8-48c7-bafd-1e6ecf35c721.png">

Second:
<img width="308" alt="image" src="https://user-images.githubusercontent.com/38455621/176118737-723f57c4-aae6-47b8-b72a-bf8a749d5e15.png">

Maybe it is related to the `cls-rtracer` lib.

**Comment by Simon-Campbell** [comment]
Hmm, could be. I am using the same library in my application.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Simon-Campbell** [comment]
@holzerch With your information I have updated my repro steps to simply add cls-rtracer-- it breaks just by simply adding it the middleware! I am not strong enough in this space to understand which library (if any) is broken.

At this point, I might have to simply downgrade and backport some functionality patches on a fork of pino-http. This isn't desired state for me

The other option is: could we look to introduce some logic that supresses the second "finish" line in pino-http? What are your thoughts on that change @mcollina ?

**Comment by mcollina** [comment]
I don't understand why you are asking for pino-http to work around a bug in cls-rtracer.
Open an issue there and ask them to fix the bug. My two cents are on this file: https://github.com/puzpuzpuz/cls-rtracer/blob/2745858bc2728d6c54cd05afd36d4be3c357a8f6/src/util.js#L6.

I think @puzpuzpuz would be happy to take a look.
