### ISSUE TITLE
timeouts when using pino-http 2.4 + express under alpine linux

### ISSUE THREAD

**Issue by stevejhiggs** [pinojs/pino-http#24]
Apologies for the brevity of this, I'll add more information as I get it but I thought it was a sufficiently worrying issue to raise straightaway.

Setup:

Using pino-http under express running on the alpine-node:7.4.0 docker image in aws.

hit the express endpoint with a lot of traffic and everything starts backing up + memory usage grows continually. Eventually the server just starts returning timeout errors.

Under 2.3 everything works fine.

I'll add more info as my investigation continues.

**Comment by mcollina** [comment]
This is the culprit then: https://github.com/pinojs/pino-http/pull/22.

It should not be related to alpine, and you should be able to reproduce it everywhere if that's the case.

Does reverting back to 2.3 fix the issue?

**Comment by stevejhiggs** [comment]
yep, 2.3 works fine when I downgraded the package.

It caught us out because we were actually using the express-pino-logger package, which then pulled in pino-http so our deps changed even though the versions were locked. 

We've changed to using pino-http directly now and locked in to 2.3. We're also going to switch to yarn to stop sub-deps upgrading on us :)

**Comment by mcollina** [comment]
Ok, that's definitely the bug then.

cc @ronag

**Comment by ronag** [comment]
@mcollina: Tried to fix: https://github.com/pinojs/pino-http/pull/26
