### ISSUE TITLE
Multiple streams

### ISSUE THREAD

**Issue by ajfranzoia** [pinojs/pino-http#245]
Is it possible to utilize multiple output streams? I need to log to the console and at the same time to GCP Stackdriver.
I was using `pinoms` but it's no longer supported.

This is the configuration I was using for the previous version:

```js
pinoHttp: {
  logger: pinoms({
    streams: [
      {
        stream: pinoms.prettyStream({
          prettyPrint: {
            translateTime: 'SYS:standard',
          },
        }),
      },
        {
          stream: pinoStackdriver.createWriteStream({
            logName: '...',
            projectId: '...',
            credentials: '...',
            resource: {
              type: 'global',
            },
          }),
        }
    ],
  }),
}
```

**Comment by mcollina** [comment]
Multistream is now backed in pino itself.

**Comment by ajfranzoia** [comment]
@mcollina well, pino creators say that this is an issue with `pino-http`, see https://github.com/iamolegga/nestjs-pino/issues/748#issuecomment-1004091408
