### ISSUE TITLE
customProps should allow returning a Promise

### ISSUE THREAD

**Issue by adarnon** [pinojs/pino-http#249]
We are using Pino together with Next.js and `iron-session` for authentication. We've been using the `customProps` function in order to populate log messages with context information about the user, etc.

Iron session recently released a major version in which `getIronSession()` now returns a Promise. Since `customProps` can only return an `object`, fetching information from our iron session in that callback is impossible.

Is there a plan to allow for promises? This sounds like a fairly standard expectation in 2022.

**Comment by jsumners** [comment]
No, there is no plan for that. It was add a significant amount of overhead.
