### ISSUE TITLE
Log debug logs only on when at least one error logged in request

### ISSUE THREAD

**Issue by dasaco** [pinojs/pino-http#254]
Hello, thank you for this great library.

I was wondering is it possible to log debug logs only when error log was triggered in **request**? For example if in production debug logs would be present it would help developers, but we wouldn't want to log them all the time as they are useless if request did not fail.

From what I saw it is not possible currently as logs are not buffered, but logged immediately, would appreciate if you could comment if this layer is an appropriate one for such implementation. If this makes sense I could submit a PR with a solution.

Or maybe there is already an existing option that will help with that, which I didn't see yet.

As for layer I am using nestjs-pino. So dependency goes nestjs-pino <- pino-http <- pino. So maybe you have some suggestions where this functionality could exist.

Thank you!

EDIT: Actually I see that this library takes care of request/response logging, it doesn't affect other logs, lmk if this is the case.

**Comment by mcollina** [comment]
Thanks for reaching out. Unfortunately it's not a responsibility of this library to do it as this just instrument the server. However creating this behavior would be an amazing transport

**Comment by dasaco** [comment]
Thanks for a quick reply Matteo, yes that makes sense.
