### ISSUE TITLE
Debug fn not working

### ISSUE THREAD

**Issue by htadeusiak** [pinojs/pino-http#257]
Hey guys,

Appreciate all the work on the library. I'm currently trying to use the 'req.log.debug()' log function that is provided in the 'pino' package. However, this function doesn't end up logging anything when used from the 'pino-http' package. The I can use 'info()' to log information, but I want to be able to use the "debug" level in my code. 

Is this intended functionality or a bug? I looked on the docs and couldn't find anything on the 'debug()' log function, but rather only the 'info' function.

Thank you!

**Comment by jsumners** [comment]
> Is this intended functionality or a bug?

Is what a bug? What have you tried? Is it producing an error?

> I looked on the docs and couldn't find anything on the 'debug()' log function, but rather only the 'info' function.

What documentation are you referring to?

**Comment by htadeusiak** [comment]
When I call `req.log.debug("test")` absolutely nothing is logged. It is as if I just never called anything, the line is as good as being commented out.

However, when I call `req.log.info("test")` I get the expected object logged to my server with  the fields `req`, `req.id`, `msg`, etc.

In the `pino` library, they support a `debug()` function that logs when level is `debug`.

So is the fact that debug does not log anything a bug?

I also tested the following:
```
app.use(pino({ useLevel: "debug" }));

```
and everything stops logging on my server.

However, if I set it to:
```
app.use(pino({ useLevel: "debug" }));
```
I get the logs on all my requests as expected.


It seems like theres an issue around the debug level?

**Comment by jsumners** [comment]
https://getpino.io/#/docs/api?id=level-string is appropriate. I do not know where you found `useLevel`.

**Comment by htadeusiak** [comment]
Oh that's why lol. Can you guys please update your docs here: https://github.com/pinojs/pino-http#api

I was only looking at the the API for `pino-http`. I know its level for `pino` and thought it was weird you guys had it documented as something else for `pino-http`

**Comment by jsumners** [comment]
https://github.com/pinojs/pino-http/blob/112e2eb2297e30516248684a29ee0658a5cc8b30/README.md?plain=1#L94

What else are you wanting to see?

**Comment by htadeusiak** [comment]
Yup I see it now, honestly skipped over it as I thought that all options would be listed in the bullet points. 

I would have probably been less likely to miss it if it was the first listed bullet point, but think its fine as is.

Thank you!

**Comment by CodeMan99** [comment]
> I do not know where you found `useLevel`.

The TypeScript definition file has the `useLevel` property.

https://github.com/pinojs/pino-http/blob/bccda3c8e54b4d29c0a3a9497d84d39026e7e743/index.d.ts#L28

It seems like that property exists, is parsed, and then promptly ignored. Maybe `useLevel` shouldn't be part of the type?
