### ISSUE TITLE
Multiple middleware instances with different redact config

### ISSUE THREAD

**Issue by mmadson** [pinojs/pino-http#260]
- Create 2 pinoHttp loggers with different redact configs. 
- Attach both middleware to express app

Expected: 2 log entries with different redactions
Actual: 2 log entries with the same redactions

I think this is because the logger variable of the loggingMiddleware function is shared across multiple instantiations of the middleware. It would be good if we can have separate logger instances for each call of pinoHttp

**Comment by jsumners** [comment]
It seems like you are passing `opts = { logger: pino() }` to both instances. Otherwise, a unique instance is created each time at https://github.com/pinojs/pino-http/blob/112e2eb2297e30516248684a29ee0658a5cc8b30/logger.js#L202

**Comment by mmadson** [comment]
That was my expectation as well, however my config does not specify a pino logger in the opts:

```
VERY_REDACTED_HTTP_LOGGER = pinoHttp({
    genReqId: (req: express.Request) => {
      if (!req.id) {
        req.id = randomUUID();
      }
      return req.id;
    },
    customProps: (_req: IncomingMessage, _res: ServerResponse) => {
      return deepmerge(getLogContext(), { requestLog: false });
    },
    customLogLevel: (_req: IncomingMessage, res: ServerResponse, _error: Error) => (res.statusCode >= 500 ? "error" : "info"),
    redact: config.logger.redacted,
  } as Options);
  
  SOMEWHAT_REDACTED_LOG_HTTP_LOGGER = pinoHttp({
    genReqId: (req: express.Request) => {
      if (!req.id) {
        req.id = randomUUID();
      }
      return req.id;
    },
    customProps: (_req: IncomingMessage, _res: ServerResponse) => {
      return deepmerge(getLogContext(), { requestLog: true });
    },
    customLogLevel: (_req: IncomingMessage, res: ServerResponse, _error: Error) => (res.statusCode >= 500 ? "error" : "info"),
    redact: config.logger.redacted.filter((key) => key !== "req.url"),
  } as Options);
  ```
  
  I think the culprit is this line:
  
  https://github.com/pinojs/pino-http/blob/master/logger.js#L88
  
Which assigns the logger (either a new logger or the opts logger) to a property of the loggingMiddleware function which if I'm not mistaken is shared between multiple pino-http middlewares.

**Comment by jsumners** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mmadson** [comment]
@jsumners Sure, I believe I have a fix and unit tests ready locally, I just need to check on my employer's OSS contribution policies.

- Am I correct in assuming I should be targeting my changes for the main branch?
- Assuming my changes are acceptable, how quickly do you think we might be able to cut a release?

**Comment by jsumners** [comment]
> * Am I correct in assuming I should be targeting my changes for the main branch?

Yes.


> * Assuming my changes are acceptable, how quickly do you think we might be able to cut a release?

As quickly as maintainers are able to review, accept, and manage the changes.

**Comment by mmadson** [comment]
Opened PR https://github.com/pinojs/pino-http/pull/263

**Comment by mmadson** [comment]
Just tested out v8.3.0 locally and everything seems to be working as I expected. Thanks for allowing me to contribute folks; please consider this resolved. =)
