### ISSUE TITLE
Set on completed/error msg  at runtime

### ISSUE THREAD

**Issue by naseemkullah** [pinojs/pino-http#267]
I've recently discovered and fallen in love with req.log.setBindings() and am consolidating disparate logs during requests into just one rich log upon request completion.

A cherry on top would be to be able to override the on completed/error message depending on the route and response. My current workaround is to set an "eventName" property before request completes. Thoughts?

**Comment by mcollina** [comment]
That's a great one ;).

**Comment by naseemkullah** [comment]
Ha! I just realized this is already possible, e.g.:

```js
    customSuccessMessage: (req, res) => {
      if (req.url === '/foo') {
        if ([200, 201].includes(res.statusCode)) {
          return 'good foo event.';
        }
        return 'bad foo event.';
      }
      return 'request completed.';
    },
 ```
 
 Closing since already implemented 🚀
