### ISSUE TITLE
Documentation: res.log() is only mentioned in quietReqLogger?

### ISSUE THREAD

**Issue by jmealo** [pinojs/pino-http#289]
Hello,

I was reading the API docs, and noticed that `res.log()` is only mentioned in `quietReqLogger`:

> **quietReqLogger**: when true, the child logger available on req.log will no longer contain the full bindings and will now only have the request id bound at reqId (note: the autoLogging messages and the logger available on **`res.log`** will remain the same except they will also have the additional reqId property). default: false

Should we document `res.log()` elsewhere -- otherwise, it may give the impression of being a typo.

Thanks for the great work!

**Comment by mcollina** [comment]
Can you clarify? `res.log()` should not be a thing.

**Comment by mcollina** [comment]
`res.log` is not a function

**Comment by jmealo** [comment]
Sure, it's a reference to `req.log`, the issue being presented is:

* Is `res.log` adequately documented?

* Does anyone care if the only answer to this question is to read the source?

* Does the single occurrence of `res.log` make it appear to be a typo?

**Comment by mcollina** [comment]
>Is res.log adequately documented?

Likely no, can you add it?

> Does anyone care if the only answer to this question is to read the source?

I don't understand this question

> Does the single occurrence of res.log make it appear to be a typo?

No, `res.log` is a valid usecase. There might be cases where we don't have a reference of `req` but only of `res`.

**Comment by jmealo** [comment]
@mcollina: I can try to open a PR, trying to lobby to switch out Bunyan with Pino at my day job. I'm guessing that the typescript definitions for `OutgoingMessage` should add `log` so that you can reference `res.log` without encountering an error.

**Comment by jmealo** [comment]
@mcollina: I have a PR ready, however, it appears there's an error on #master with the typescript types?

```
index.test-d.ts:140:3 - error TS2739: Type '{ id: string | undefined; method: string; url: string; headers: { header: string; }; remoteAddress: string; remotePort: number; raw: IncomingMessage; }' is missing the following properties from type 'SerializedRequest': params, query

140   req: {
      ~~~

  index.d.ts:68:5
    68     req: SerializedRequest;
           ~~~
    The expected type comes from property 'req' which is declared here on type 'StdSerializedResults'


Found 1 error in index.test-d.ts:140

```

**Comment by jmealo** [comment]
It looks like the standard serializers type defs changed and params and query are mandatory
