### ISSUE TITLE
Updating for v10

### ISSUE THREAD

**Issue by Ranieri93** [pinojs/pino-http#299]
Hello everyone!
I would like to work on this, as needed in [issue #1762](https://github.com/pinojs/pino/issues/1762) and referenced [here](https://github.com/pinojs/koa-pino-logger/issues/63).

I guess here we don't need much explanation about the need for the update.
I should also mention that there is a dependency with [pino-std-serializers](https://github.com/pinojs/pino-std-serializers), so I guess I'll work on that too.

@jsumners

**Comment by jsumners** [comment]
Thanks. I have created `next` branches here, in the koa module repo, and the standard serializers repo. Luckily, the standard serializers module is simple; it will probably only need some CI changes to eliminate old Node.js versions and some dependency bumps.

**Comment by mcollina** [comment]
v10 shipped
