### ISSUE TITLE
`wrapChild` doesn't pass on options to the created child logger as expected

### ISSUE THREAD

**Issue by ramblingenzyme** [pinojs/pino-http#310]
https://github.com/pinojs/pino-http/blob/9109d5446a9c2cc02ba5b98f3bd345d9c24db61a/logger.js#L83
![image](https://github.com/pinojs/pino-http/assets/5336472/c1b6a96c-fbc9-4f44-9f6d-608072aaf83e)

Based on the published API of `pino`, passing option overrides to a child logger is the second argument to .child, not the first. https://github.com/pinojs/pino/blob/master/docs/api.md#loggerchildbindings-options--logger
![image](https://github.com/pinojs/pino-http/assets/5336472/ed9b4399-5895-48c1-b190-01d2ad6a76d3)

I think this bit of code needs an update and tests written for that use case, as well as validating if the user has passed `logger` & any pino options to `pino-http` that are ignored by `.child`.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by ramblingenzyme** [comment]
I'm happy to take a stab at it, I'll let you know if I get a PR up or if I back out.

**Comment by ramblingenzyme** [comment]
@mcollina 🤦🏽 I don't know how I ended up in the commit I linked, but I was looking at 6 year old code, the current code is as expected. Sorry for the incorrect bug report.

https://github.com/pinojs/pino-http/blob/master/logger.js#L218
https://github.com/pinojs/pino-http/blob/44c61b76c0c05dace6b4c701d12c6a546c6ad013/logger.js#L218
