### ISSUE TITLE
How best to handle extending req.log?

### ISSUE THREAD

**Issue by ramblingenzyme** [pinojs/pino-http#311]
Context:
We want to attach the pino-http middleware first so that `req.log` is always defined and can be used in all Express middleware / all route handlers. However, we also always want to include information about which tenant/customer a request is for, but our authorization middleware gets invoked later.

![image](https://github.com/pinojs/pino-http/assets/5336472/914395f8-7c04-48f4-ab8d-a8d22dc48d78)

So we hack it by reassigning `req.log`. However, this middleware is defined and exported from an internal library.

This has caused some friction for the internal consumers of our library when they've setup AsyncLocalStorage to capture `req.log`, following this article. https://blog.logrocket.com/logging-with-pino-and-asynclocalstorage-in-node-js/

The issue was that this only captured the original req.log, and not the new child logger from our middleware, and required a less than ideal workaround to lazily dereference `req.log`.

![image](https://github.com/pinojs/pino-http/assets/5336472/e4122949-454a-4636-b4b9-4cdbd5f7d3b0)

We could extend our internal library to be aware of AsyncLocalStorage or move the AsyncLocalStorage logger into the library itself, but is there a better/sanctioned solution or something in the API I've missed that simplifies this?

**Comment by ramblingenzyme** [comment]
@mcollina, thanks for the quick response. I understand there's no sanctioned solution for AsyncLocalStorage, but is there a better solution for middleware than reassigning `req.log` if all downstream middleware should have extra bindings?

I don't think I was very clear in asking that question, but I understand the answer is probably the same.

**Comment by ramblingenzyme** [comment]
@mcollina would the team be open to merging something like this in (of course with documentation updates and tests) https://github.com/ramblingenzyme/pino-http/pull/1 to provide an official API which lets you extend the bindings and not reassign `req.log`/`res.log`?

**Comment by mcollina** [comment]
No, not really. Proxy is very slow.

**Comment by ramblingenzyme** [comment]
@mcollina, I've just noticed that Pino has a `setBindings` method, which is in the TS types but not in the API docs. Should I actually be using that something like `logger.setBindings({ ...logger.bindings(), newBindingProp: "string" })`
