### ISSUE TITLE
Type 'Opts' does not satisfy the constraint 'string'.ts(2344) 

### ISSUE THREAD

**Issue by chiragjoshi28** [pinojs/pino-http#313]
Throwing error for opts type mismatch

export interface HttpLogger<IM = IncomingMessage, SR = ServerResponse, Opts = Options<IM, SR>> {
    (req: IM, res: SR, next?: () => void): void;
    logger: pino.Logger<Opts>;
}

Type 'Opts' does not satisfy the constraint 'string'.ts(2344)
index.d.ts(19, 72): This type parameter might need an `extends string` constraint.

**Comment by AvivVegh** [comment]
reproducing on my end as well

**Comment by ZakariasLaws** [comment]
Same problem for me

**Comment by RafaelFeiten** [comment]
Same problem here. If you doesn't have an old package-lock.json (with correct dependencies), you'll get this error.
help?

**Comment by tordsta** [comment]
Same problem here

**Comment by RafaelFeiten** [comment]
A **temporary** solution:
Install version 8.4 `npm i pino-http@8.4.0`

Then go to your package-lock.json, and find for `"node_modules/pino-http"`, you'll see the version 8.5.1, then replace for:
```
    "node_modules/pino-http": {
      "version": "8.4.0",
      "resolved": "https://registry.npmjs.org/pino-http/-/pino-http-8.4.0.tgz",
      "integrity": "sha512-9I1eRLxsujQJwLQTrHBU0wDlwnry2HzV2TlDwAsmZ9nT3Y2NQBLrz+DYp73L4i11vl/eudnFT8Eg0Kp62tMwEw==",
      "dependencies": {
        "get-caller-file": "^2.0.5",
        "pino": "^8.0.0",
        "pino-std-serializers": "^6.0.0",
        "process-warning": "^2.0.0"
      }
    },
```

And run `npm i` again.
