### ISSUE TITLE
Unable to remove whole req object from response logs

### ISSUE THREAD

**Issue by mzvonar** [pinojs/pino-http#327]
Hi,
firstly thank you for this amazong library.

I’m trying to remove the `req` object from succesful response log, because it’s huge.

I saw it was discussed here: [https://github.com/pinojs/pino-http/issues/5 ](https://github.com/pinojs/pino-http/issues/5)

But I looked through the code and maybe it has chnhed simce then. It seems the res logger is always set to the `fullReqLogger` here: https://github.com/pinojs/pino-http/blob/master/logger.js#L150

So using `customReceivedObject` or serializers has no effect because by the time they are used the `req` is already added to the `fullReqLogger` context and is always part of the resulting log.

The only way I found is to use redaction, but it feels kind of hacky.

Shouldn’t the `responseLogger` variable also be set to `log` in case the `quietReqLogger` option is enabled?

Or is there a better way to do this?

Thanks

**Comment by jsumners** [comment]
Please provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example). Doing so will help us diagnose your issue. It should be the bare minimum code needed to trigger the issue, and easily runnable without any changes or extra code.

You may use a GitHub repository to host the code if it is too much to fit in a [code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) (or two).

**Comment by mzvonar** [comment]
> Please provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example). Doing so will help us diagnose your issue. It should be the bare minimum code needed to trigger the issue, and easily runnable without any changes or extra code.
> 
> You may use a GitHub repository to host the code if it is too much to fit in a [code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) (or two).

@jsumners thanks for looking into it. I’m sorry I was extended mu pono logger and I messed up `this` so the serializers were never called when I provided my logger instance to pinoHttp.
I didn’t get to it today but I will verify thoroughly that everytinhg works after I fixed that.
