### ISSUE TITLE
Undocumented Breaking Changes for 9.0.0

### ISSUE THREAD

**Issue by ahilke** [pinojs/pino-http#328]
I was looking at the project and got confused around version 9.

Firstly, the [release](https://github.com/pinojs/pino-http/releases/tag/v9.0.0) does not mention any breaking changes, but as far as I can tell it actually dropped support for Node 14 and 16 based on this PR: https://github.com/pinojs/pino-http/pull/309. It would be very beneficial to provide a list of breaking changes with major releases to help with upgrading. 

Secondly, I believe with the release of version 9 a few issues that referred to an upcoming version 9 are outdated, for example https://github.com/pinojs/pino-http/issues/299.
It might make sense to go through them and close or update them as required.

**Comment by mcollina** [comment]
Thanks for the feedback
