### ISSUE TITLE
Broken with h3

### ISSUE THREAD

**Issue by jolo-dev** [pinojs/pino-http#335]
It seems that it does not work with [h3](https://h3.unjs.io/).

I have reproduced the error, and I followed the instructions from the docs

https://stackblitz.com/edit/github-9quron?file=app.ts

**Comment by mcollina** [comment]
Thanks for reporting. Apparently h3 does not use a connect/express style of middleware, as you can see in https://h3.unjs.io/guide/app#registering-event-handlers.

Therefore, h3 is not supported by its module.

**Comment by jolo-dev** [comment]
@mcollina thanks for the reply.
It also means then that we need to remove that from the documentation, right?
https://getpino.io/#/docs/web?id=pino-with-h3

**Comment by mcollina** [comment]
Here is it: https://github.com/pinojs/pino/pull/1968.
