### ISSUE TITLE
CLI not installing

### ISSUE THREAD

**Issue by chaseWilliams** [pinojs/pino-http#336]
I've been able to use `pino-http` for months, but recently something broke and now `pino-http` isn't recognized as a command anymore. I'm not sure what happened, may be my fault.

with this as `delete_me.js`
```
'use strict'

const http = require('http')
const server = http.createServer(handle)

const logger = require('pino-http')()

function handle (req, res) {
  logger(req, res)
  req.log.info('something else')
  res.end('hello world')
}

server.listen(3000)
```

Running `node delete_me.js | pino-http` returns `zsh: command not found: pino-pretty` and no further output, even after hitting the server and getting a response

**Comment by jsumners** [comment]
`pino-http` does not provide a CLI interface. You can see that there is not a `bin` field in the `package.json`: https://github.com/pinojs/pino-http/blob/bccda3c8e54b4d29c0a3a9497d84d39026e7e743/package.json

**Comment by chaseWilliams** [comment]
ok that makes sense. Why then does piping node logs to it like `node delete_me.js | pino-http` not work for me? Am I doing something wrong here?

**Comment by jsumners** [comment]
I believe you are looking for https://github.com/pinojs/pino-pretty

**Comment by chaseWilliams** [comment]
I'm so sorry you're right, didn't notice those were two separate names. thanks for pointing me back to that
