### ISSUE TITLE
I can't log in to response to the body

### ISSUE THREAD

**Issue by 1340145680** [pinojs/pino-http#340]
### The base framework I use is express

- [x] I've read [https://github.com/pinojs/pino-http/issues/283#issuecomment-1631646319](https://github.com/pinojs/pino-http/issues/283#issuecomment-1631646319)
- [x] I've read [https://github.com/pinojs/pino-http/issues/283#issuecomment-1631646319](https://github.com/pinojs/pino-http/pull/76/files)

#### I modified my code according to the Add log request body example

```JavaScript
const httpLogger = pinoHttp({
  level: "trace",
  quietReqLogger: true,
  serializers: {
    req(req) {
      console.log(req);
      req.body = req.raw.body;
      return req;
    },
  },
  })
```

#### I get the following data on my console, where the raw data type is IncomingMessage

![console image](https://github.com/pinojs/pino-http/assets/91125707/4f9c285d-9878-47bc-b956-3dfab6046d56)

#### There is indeed body in raw

![raw data view](https://github.com/pinojs/pino-http/assets/91125707/44560284-c5ae-4a0a-a496-bd8bfe0dd137)

#### But I can't get it according to the docs

```JavaScript
req(req) {
    console.log("req.raw.body:", req.raw.body);
    req.body = req.raw.body;
    return req;
}
```

![console image](https://github.com/pinojs/pino-http/assets/91125707/92e80e2b-3013-4076-8d06-685c944cf806)

**Comment by 1340145680** [comment]
@mcollina

**Comment by jsumners** [comment]
Please provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example). Doing so will help us diagnose your issue. It should be the bare minimum code needed to trigger the issue, and easily runnable without any changes or extra code.

You may use a GitHub repository to host the code if it is too much to fit in a [code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) (or two).

**Comment by 1340145680** [comment]
对不起，我把中间件的位置搞混了
```JavaScript
app.use(logger); //pino logger
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
````
