### ISSUE TITLE
This expression is not callable

### ISSUE THREAD

**Issue by joeythomaschaske** [pinojs/pino-http#341]
I am trying to import this into a typescript project and typescript is complaining that the library is not callable

```ts
import express from 'express';
import pino from 'pino-http';

const app = express();
app.use(pino());
```

> This expression is not callable.
>  Type 'typeof import("node_modules/pino-http/index")' has no call signatures.

Can this library be used with import syntax?

System info

pino-http: 10.1.0
node: 20.14.0
typescript: 5.4.3

**Comment by joeythomaschaske** [comment]
For whatever reason this works

```ts
import express from 'express'
import { pinoHttp } from 'pino-http';

const app = express();
app.use(pinoHttp());
```

I just don't understand why the original example doesn't work, the type definitions assign the default export to `PinoHttp`

```ts
export default PinoHttp;
export { PinoHttp as pinoHttp };
```

**Comment by mcollina** [comment]
it depends on some settings you have on your `tsconfig.json`.
