### ISSUE TITLE
`req` serializer can generate way too much output

### ISSUE THREAD

**Issue by jsumners** [pinojs/pino-http#42]
See https://github.com/pinojs/express-pino-logger/issues/14

**Comment by resure** [comment]
I've used slightly different approach for dealing with this problem:
- Firstly, I have two serializers:
  - `reqFull` — almost identical to default `req`, but with addition of `req.id`
  - `req` — simplified serializer which prints only request id
- Upon receiving request, app is generating request ID and logging all default req stuff together with that id (using `reqFull` serializer)
- After that, request is being processed. When controllers are trying to log something, that records are not containing anything excessive, just request id (which can be used later to collect all records about that request processing)
- When request processing is finished, it logs final line with `res`, `responseTime` and request id

In the end, you're still have ability to join all log records which are referred to one transaction and logs are not overloaded with all that duplicated headers and stuff.

**Comment by davidmarkclements** [comment]
@resure that's really nice - thanks for the insight

First we need to fix the over-logging issue, but having a full request and id only serializers bundled
with pino-http (et. al.) could be a really nice addition, something we could recommend in the documentation as a useful pattern – PR welcome @resure (although I'm probably going to quibble over naming things when you do)

**Comment by renarsvilnis** [comment]
@resure  Sorry to resurrect the old thread, but how did you in code achieve two req (`reqFull`, `req`) serializers?

I'm trying to achieve the same result, as I find it overkill to include the same request for each child log. Request id is just enough for debugging.
