### ISSUE TITLE
Cannot serialize custom req values

### ISSUE THREAD

**Issue by bard** [pinojs/pino-http#47]
I would expect that:

```
app.use(pinoHttp({
  serializers: {
    req: (req) => ({
      url: req.url,
      customValue: req.customValue
    })
  }
}))
```

...would log `req.customValue`, if such a property is set on `req`. But it doesn't. Minimal test case:

```
const app = require('express')()
const pinoHttp = require('pino-http')

app.use((req, res, next) => {
  req.customValue = '1234'
  next()
})

app.use(pinoHttp({
  serializers: {
  prettyPrint: true,
    req: (req) => ({
      url: req.url,
      customValue: req.customValue
    })
  }
}))

app.get('/', (req, res) => {
  res.end('ok')
})

app.listen(3000)
```

Then:

```
$ curl http://localhost:3000
```

...causes the following log output:

```
$ node app.js 
[2018-03-05T16:07:11.830Z] INFO (4656 on laptop): request completed
    req: {
      "url": "/"
    }
    res: {
      "statusCode": 200,
      "header": "HTTP/1.1 200 OK\r\nX-Powered-By: Express\r\nDate: Mon, 05 Mar 2018 16:07:11 GMT\r\nConnection: keep-alive\r\nContent-Length: 2\r\n\r\n"
    }
    responseTime: 6
```

Versions: pino-http 3.2.0 (also happening on 3.1.0)

**Comment by davidmarkclements** [comment]
could you try it without the `prettyPrint` option

**Comment by cwillwer** [comment]
Likewise, I just installed pino-http 3.2.0, am using it without any options, and considering it is used after body-parser, I would expect that POST operations would have their body logged, but they aren't.

Example code:
```
var bodyparser = require('body-parser');
var logger = require('pino-http')();

...
app.use(bodyparser.json());
app.use(bodyparser.urlencoded({extended:true}));
app.use(logger);
```

Whether or not this is the same issue (I _feels_ like it might be), I do need to find out how to get the body of POST operations logged since the logger is kind of pointless without that crucial piece of information.

**Comment by davidmarkclements** [comment]
@cwillwer no, if you want to log the body you use a custom serializer.
The pino philosphy is lightweight, batteries not included.

**Comment by mcollina** [comment]
I would note that logging the body is a very bad practice, as those can be quite big. If this is important for a specific route, you should log it yourself.

**Comment by bard** [comment]
@davidmarkclements same outcome

**Comment by mcollina** [comment]
```
const app = require('express')()
const pinoHttp = require('pino-http')

app.use((req, res, next) => {
  console.log('a')
  req.customValue = '1234'
  next()
})

app.use(pinoHttp({
  serializers: {
    req: (req) => {
      // req has already been processed
      // see https://github.com/pinojs/pino-std-serializers#exportsreqrequest
      return {
        url: req.url,
        customValue: req.raw.customValue 
      }
    }
  }
}))

app.get('/', (req, res) => {
  res.end('ok')
})

app.listen(3000)
```

@jsumners we need to document the use of `req.raw` here too (https://github.com/pinojs/pino-std-serializers#exportsreqrequest).

**Comment by bard** [comment]
@mcollina That did the trick. Grazie!

**Comment by jsumners** [comment]
@mcollina isn't it already documented? It specifically states that `raw` is present solely for usage by custom serializers.

**Comment by mcollina** [comment]
The README of this repo should mention it as well.

**Comment by bard** [comment]
Should the README say:

```
var logger = require('pino-http')({
  serializers: function (req) {
    Object.keys(req.raw).forEach((k) => {
      if (k.startsWith('foo')) {
        req[k] = req.raw[k]
      }
    })
    return req
  }
})
```

Or:

```
var logger = require('pino-http')({
  serializers: {
    req: function (req) {
      Object.keys(req.raw).forEach((k) => {
        if (k.startsWith('foo')) {
          req[k] = req.raw[k]
        }
      })
      return req
    }
  }
})
```

?

**Comment by davidmarkclements** [comment]
.. I'm unclear as to why this would be ambiguous.. unless there's been an API change I've missed it's quite definitely the latter - why is the readme wrong?

**Comment by jsumners** [comment]
Because I did it wrong. @bard would you like to send a PR?

**Comment by bard** [comment]
Sure, will do soon.
