### ISSUE TITLE
`res.on` should be `res.once`

### ISSUE THREAD

**Issue by niftylettuce** [pinojs/pino-http#54]
<https://github.com/pinojs/pino-http/blob/master/logger.js#L59-L60>

**Comment by mcollina** [comment]
No it shouldn’t. We are calling removeListener as the first thing in the event handler

**Comment by niftylettuce** [comment]
I meant in the sense of just best practice, if just one time then `once` is
preferred, no?  Unless there is some perf thing I don't know about?  Either
way fine as is, agreed.

**Comment by mcollina** [comment]
` once` does an `on`  and `removeListener`. We have to call `removeListener` anyway because we don't know which event fires, and doing it only once saves a few CPU cycles.

**Comment by niftylettuce** [comment]
@mcollina good to know, thank you
