### ISSUE TITLE
Wrong stack trace on request errors (Express)

### ISSUE THREAD

**Issue by laurentgoudet** [pinojs/pino-http#61]
I have an Express app with a catch-all error handler as per the [Express docs](https://expressjs.com/en/guide/error-handling.html):

```
app.use(function (err, req, res, next) {
  req.log.error(err)
  res.status(500).send('Internal Server Error');
}
```

However, the above code logs the error fine:

```
[1553698996126] ERROR (52887 on MacBook-Pro): Uncaught (in promise): ReferenceError: <foo> is not defined
ReferenceError: <foo> is not defined
    at <full stack trace>
```

But the request log itself has the wrong level (info?) & stack trace:

```
[1553698996235] INFO  (52887 on MacBook-Pro): request errored
    req: {
      "id": 1,
      "method": "GET",
      "url": "/<foo>",
      "headers": {
        "host": "localhost:4000",
        "user-agent": "curl/7.54.0",
        "accept": "*/*"
      },
      "remoteAddress": "::1",
      "remotePort": 64724
    }
    res: {
      "statusCode": 500,
      "headers": {
        "x-powered-by": "Express",
        "content-type": "text/html; charset=utf-8",
        "content-length": "139339",
        "etag": "W/\"2204b-wKSbSPj2LUqOYJm+RUU9W+R5pJQ\""
      }
    }
    err: {
      "type": "Error",
      "message": "failed with status code 500",
      "stack":
          Error: failed with status code 500
              at ServerResponse.onResFinished (/<foo>/node_modules/pino-http/logger.js:48:33))
              at ServerResponse.emit (events.js:187:15)
              at onFinish (_http_outgoing.js:678:10)
    }
    responseTime: 499
```

Is this the expected behavior? Removing the custom error handler doesn't fix the problem, Express then does log the correct error (stack trace) in the console by default. I'm using Express 4.16.4 & express-pino-logger 4.0.0.

**Comment by mcollina** [comment]
According to what you are saying, we shouldn't create a new error in https://github.com/pinojs/pino-http/blob/master/logger.js#L48. I agree! would you like to send a PR?

**Comment by laurentgoudet** [comment]
That would just remove the error from the request log though? I would expect a request error log to both have a level of `error` (e.g., to filter them in Kibana) and to contain the necessary information (e.g. a stack trace) to identified what caused the request to fail. Is there a way to achieve that?

**Comment by laurentgoudet** [comment]
Actually looking into the logger's code setting the error onto the response object does the trick, not sure if it's part of the official API though:

```
app.use((err: any, req: any, res: any, next: any) => {
  res.err = err;
  res.status(500).send('Internal Server Error');
});
```

As as the log level, `customLogLevel` fills that need already, i.e.:

```
const pinoHttpLogger = pinoHttp({
  logger,
  customLogLevel: (res: any, err: any) =>
    res.statusCode >= 500 ? 'error' : 'info',
});
```

**Comment by mcollina** [comment]
That’s part of the API interface.

**Comment by laurentgoudet** [comment]
Cool, closing. Thanks for the help!

**Comment by grahamlyons** [comment]
> That’s part of the API interface.

This issue helped me to find why I wasn't getting a stack trace from errors thrown in Express but I didn't see where this API was documented in pino-http. That would be really useful.
