### ISSUE TITLE
Pino Http not working with cls-proxify

### ISSUE THREAD

**Issue by BrendanBall** [pinojs/pino-http#64]
Hi, I'm trying to setup logging with pino and cls-proxify (and express), but pino http seems to lose the bindings somehow. When setting up my own middleware, the bindings appear in the logs e.g
```
const baseLogger = pino({ timestamp: false, base: null })
const log = clsProxify('clsKeyLogger', baseLogger)
app.use([
  clsProxifyExpressMiddleware('clsKeyLogger', (req) => baseLogger.child({ foo: 'bar' })),
  (req, res, next) => {
    log.info('trace 1')
    next()
  },
  (req, res, next) => {
    res.on('finish', () => log.info('trace 2'))
    next()
  },
  pinoHttp({  logger: log })])
```
But pino http logs don't contain the bindings.

Do you expect this library to work with cls-proxify?

**Comment by mcollina** [comment]
You should open the issue on cls-proxify.
