### ISSUE TITLE
Expose `req._startAt` and `req._startTime` to be similar to morgan

### ISSUE THREAD

**Issue by niftylettuce** [pinojs/pino-http#65]
<https://github.com/expressjs/morgan/blob/master/index.js#L500-L508>

**Comment by niftylettuce** [comment]
Also <https://github.com/pinojs/pino-http/blob/master/logger.js#L63> could probably be changed so that it also sets `req[startTime]`.

**Comment by niftylettuce** [comment]
The reason I need this is because I want record the time the request was received in a log, and this is the easiest approach, since this is a timer that starts and is also the same timer used for calculation of response time.

**Comment by davidmarkclements** [comment]
Since we're modifying req objects we wanted to be as least invasive as possible we use a symbol because it's  "more private". 

The `startTime` symbol is exposed: https://github.com/pinojs/pino-http/blob/master/logger.js#L108 would that be enough to work with your end?

**Comment by niftylettuce** [comment]
This would require me to require the package and install it in my log parser, which I really didn't want to do, since the log parser I'm writing is a library to be published in npm.

**Comment by niftylettuce** [comment]
Prefixing with an underscore as morgan does is probably sufficient enough.

**Comment by davidmarkclements** [comment]
We could expose it using `Symbol.for`, and then you can use `Symbol.for('pino-http.startTime')`

That way you don't have to require the package, and we don't have add more noise to the req/res objects. I'd be happy to accept a PR for altering to `Symbol.for`

**Comment by niftylettuce** [comment]
Closing in favor of #66 and #67
