### ISSUE TITLE
Add option for custom logging format

### ISSUE THREAD

**Issue by taylorjdawson** [pinojs/pino-http#73]
Using the serializers I can customize what get's logged. However, I do not have control over the logging format. For example, I would like to log like so:
```
[1574212772844] INFO (35 on db805887c09f): 11.11.111.111 - GET /url/path - Status Code: 200
```
Essentially it would mean removing the object with `res` & `err` [here](https://github.com/pinojs/pino-http/blob/a7c82bc2d82847ba6692b20de1e7d2b65c4a1624/logger.js#L49-L60) in `logger.js`:
```
      log[level]({
        res: this,
        err: err || this.err || new Error('failed with status code ' + this.statusCode),
        responseTime: responseTime
      }, 'request errored')
      return
    }


    log[level]({
      res: this,
      responseTime: responseTime
    }, 'request completed')
```

...allowing the user to decide how to format the log.

**Comment by mcollina** [comment]
I'm -1 in removing the lines from pino-http for _formatting_ reasons. I'm happy to review a PR that make things more flexible here.

**Comment by taylorjdawson** [comment]
Okay I did some digging and I think what I am looking for is something like [this](https://github.com/pinojs/pino-http-print/blob/master/index.js). I think it would be possible by using the stream like you did to manipulate the logging format. Is that true? If so I guess it wouldn't apply to the `pino-http` module.

**Comment by waynebloss** [comment]
I'd like this option as well.

The suggested `11.11.111.111 - GET /url/path - Status Code: 200` format would be preferred in any configuration instead of the default `request completed` message, however i'd also add an option to remove details of `req` and `res` unless I opt into getting them for specific endpoints.

This code looks easy enough to fork though, so I won't wait around too long for it.

**Comment by waynebloss** [comment]
I couldn't get `pino-http-print` to work at all.

Attempt 1:

```ts
import express from "express";
import pino from "pino";
import expressPino from "express-pino-logger";
import pinoHttpPrint from "pino-http-print";

const log = pino({
  prettyPrint: {
    translateTime: "SYS:yyyy-mm-dd HH:MM:ss.l",
  },
});

const app = express();

app.use(expressPino(pinoHttpPrint()));
```

Attempt 2:

```ts
app.use(expressPino(pinoHttpPrint({ all: true })));
```

Attempt 3:

```ts
app.use(
  expressPino({
    logger: log,
    stream: pinoHttpPrint({ all: true }),
  }),
);
```

Anyway, this is probably the wrong place for this comment but instead of starting new issues that I don't really care about I figured I'd just leave it here, fork `pino-http` and do what I want just for my own projects.

This seems like a really good logger but it's just too bad that I have to compose 3 different packages together just to get some useful Express logging without all of the `req`/`res` diarrhea.

**Comment by rohit-gohri** [comment]
> I couldn't get `pino-http-print` to work at all.

An update was released for `pino-http-print` right after this that added some options, I suggest you check it out again.

The difference is that the `pino-http-print` module returns a factory instead of a print stream directly. So you have to call it again to get a stream.

My current setup:

```js
const express =  require("express");
const pino = require('pino');
const pinoPrint = require('pino-http-print');
const expressPino = require('express-pino-logger')

const prettyPrintFactory = pinoPrint({
	all: true,
	relativeUrl: true,
	translateTime: 'SYS:standard',
});

const prettyPrint = prettyPrintFactory();

const log = pino(prettyPrint);

const app = express();

app.use(expressPino(prettyPrint));
// OR reuse existing pino instance instead
// app.use(expressPino({logger: log}));

app.get('/test', (req, res) => {
    res.send('OK');
})

app.listen(3000, () => {
    log.info('Listening now...');
});

```

Output:

```sh
[2020-02-16 18:52:07.083 +0530] INFO  (22235 on lg-gram-elementary): Listening now...
[2020-02-16 18:52:11.892 +0530] GET /test 200
[2020-02-16 18:52:12.007 +0530] GET /favicon.ico 404
```

**Comment by davidmarkclements** [comment]
@waynebloss to be clear, there is a much simpler pattern for this http://getpino.io/#/docs/pretty?id=pretty-printing

you pipe the JSON output to a prettifer, that's it.

**Comment by rohit-gohri** [comment]
> you pipe the JSON output to a prettifer, that's it.

`pino-http-print` also works as a [command](https://github.com/pinojs/pino-http-print#cli). Equivalent example would be:

`node index.js | pino-http-print -a -r -t 'SYS:standard'`

with the below `index.js` file.

```js
// index.js
const express =  require("express");
const expressPino = require('express-pino-logger')

const app = express();
app.use(expressPino());

```

Though setting up pino with a prettifier conditionally in dev environment is also pretty convenient.

@davidmarkclements Would a [pino-http-print](https://github.com/pinojs/pino-http-print) example in the pretty printing section be a good idea for the docs? I know a few people who migrated from morgan to pino/express-pino but had a hard time setting up pretty printing for dev environments for request logs.

**Comment by davidmarkclements** [comment]
absolutely, PR's to pino docs is always welcome

**Comment by clemenspeters** [comment]
Might `customSuccessMessage` be a solution for you?
Similar to:

`const requestLogger = require("express-pino-logger")({
  logger,
  customSuccessMessage: function (res) {
    return `${res.req.ip} - ${res.req.originalMethod} ${res.req.originalUrl} - ${res.statusCode}`;
  },
});`

**Comment by giovanni-bertoncelli** [comment]
I'd like to have that too... The `pino-http-print` does not work for me...
I'll adopt the @clemenspeters solution but it will be a better if I can have req and res already serialized as parameters there (there is no way to access responseTime in the `customSuccessMessage` function...).

This solution is actually a workaround and if I want to have only that message I have to put req and res to null in the serializers...

**Comment by rstoermer** [comment]
Any updates on this? A meaningful message including the requested URL and reponse time should be a must
