### ISSUE TITLE
Support custom serializer for auto logging?

### ISSUE THREAD

**Issue by fiznool** [pinojs/pino-http#82]
Apologies if I've missed something here.

When using the `autoLogging` feature, I get a huge amount of information logged, as the autologger [logs everything in the `res` object by default](https://github.com/pinojs/pino-http/blob/master/logger.js#L58-L61). In my case, `res` contains a `_req` property, which in turn contains the entirety of the request object, including sensitive information (for example, the request body).

It would appear that a custom serializer for the  object logged in `onResFinished` might be beneficial here?

Finally, I've only tried this in development. Perhaps this isn't the same behaviour if `NODE_ENV` is `"production"`?

**Comment by fiznool** [comment]
Apologies, I am using a `nestedKey` and fell foul of https://github.com/pinojs/pino/issues/771 - once I added a set of custom serializers as described [in this comment](https://github.com/pinojs/pino/issues/771#issuecomment-592537190), all works fine.

**Comment by mcollina** [comment]
It would be awesome if you'd like to send some PRs to improve the docs of this module (or pino) to help other avoid your mistake.
