### ISSUE TITLE
Provide custom names for req/res log attributes.

### ISSUE THREAD

**Issue by CalumDickson** [pinojs/pino-http#87]
Hi pino-http team,

This middleware is perfect for our product, however due to an agreed logging standard within our organisation, we need to rename `req` and `res` to `httpReq` and `httpRes` within our logs.

We've managed to hack around the issue by mutating the log message after the fact. However, it would be far cleaner if we could control these currently hard-coded attribute names with config.

I can raise a PR if this is something you would consider accepting?

**Comment by mcollina** [comment]
Sure thing, send a PR

**Comment by mcollina** [comment]
done in v4.5.0.
