### ISSUE TITLE
Make req.id configurable

### ISSUE THREAD

**Issue by akaNightmare** [pinojs/pino-http#94]
Now, `req.id` https://github.com/pinojs/pino-http/blob/master/logger.js#L86 is static, it would be great if `id` property will be configurable.

Thanks.

**Comment by mcollina** [comment]
Sure, would you like to send a PR?

**Comment by baterson** [comment]
@mcollina I'd happy to take this issue

**Comment by mcollina** [comment]
nice!

**Comment by Kampfmoehre** [comment]
Could you make it so, that the ID can be a field outside of the req object?
Our use case shortly explained:
We use pino http in a express backend along with other non-http connections. Those non-http connections are mostly started through an http request, so we add the generated ID to the transferred objects and they appear in logs in the receiving backends. But as those are not http related, they do not include an req object in their log. 
So right now we have to possible fields were the ID could reside, req.id and correlationId.

**Comment by baterson** [comment]
@mcollina I just realized that we don't need to do any changes to the codebase. Users can just use the custom serializers if they want to change the shape of the `req` object.

@akaNightmare try this approach

```
const pino = require('pino-http')

const reqSerialier = (req) =>  {
    const { id, ...serializedReq } = serializers.req(req)
    return { ...serializedReq, customId: id }
}

const logger = pino({
    serializers: {
       'req': reqSerialier
}})
```

@Kampfmoehre  I don't think it's reasonable, you can always add your own Id along with the log message. 

@mcollina what do you say? The issue could be closed?

**Comment by mcollina** [comment]
Yes, it can be closed.
