### ISSUE TITLE
Ignores custom serializers on `opts.logger`

### ISSUE THREAD

**Issue by richardscarrott** [pinojs/pino-http#95]
I have a global `logger` which is used throughout my application with a custom `err` serializer. 

This middleware [appears to always override it](https://github.com/pinojs/pino-http/blob/master/logger.js#L29) when passing in my logger which is quite unexpected, e.g.

```js
const app = require("express")();
const pino = require("pino");
const pinoMiddleware = require("express-pino-logger");

const logger = pino({
  prettyPrint: true,
  serializers: {
    err: (err) => {
      return {
        message: err.message,
      };
    },
  },
});

app.use(
  pinoMiddleware({
    logger,
  })
);

// This correctly uses my custom err serializer
logger.error({ err: new Error("b0rked 1") });

app.get("/", function (req, res) {
  // This does not use my custom err serializer?!
  req.log.error({ err: new Error("b0rked 2") });
});

app.listen(3000);
```

**Comment by mcollina** [comment]
Would you like to send a PR? I’m ok in having an option to control this.

**Comment by richardscarrott** [comment]
Yes can do, are you happy with an option to just avoid this [entire block](https://github.com/pinojs/pino-http/blob/master/logger.js#L23-L29)?

Relatedly, when trying to workaround the issue I ran into some unfortunate behaviour as a result of this middleware mutating the serializers option object, e.g.

```
const serializers = {
  err: (err) => {
    return {
      message: err.message,
    };
  },
};

const logger = pino({
  prettyPrint: true,
  serializers,
});

app.use(
  pinoLogger({
    logger,
    // `pinoLogger` mutates the `serializers` object meaning my original `logger` also has wrapped serializers, so it starts to receive the std serialized value all of a sudden.
    serializers,
  })
);
```

I could avoid this by cloning the serializer object beforehand as it's only run on startup so don't think it's be done for perf?

Also, I wonder if it'd make sense to turn the wrapping off by default in the next breaking change as I think it's something that the caller can do v. easily anyway? e.g.

```
const serializers = {
  err: pipe(pino.stdSerializers.err, (stdSerializedErr) => ({}))
};
```
